CON-300: Address `master` and `develop` branches divergence
rticommunity/rticonnextdds-connector-js pull request #162
Opened 2023-12-18 17:41 UTC by Alxe

Connector for Javascript uses different branches for different things:
* `develop` is used for active development for new releases.
* `release/*` is used as a snapshot of a given release, and could be thought as a tag.
* `support/*` is used for maintenance of previous releases.
* `master` is a legacy branch, and should be synonymous to the latest release available.

This PR intends to address a divergence between `master` and `develop`, where `master` received some commits that were never pushed to `develop`.

2023-12-19 11:59 UTC, samuelraeburn requested changes

2023-12-19 11:59 UTC, samuelraeburn commented on .gitmodules
> +	branch = develop
I don't know what the impact of doing this is, and unless we have it clear I don't think we should do it.
Previously the workflow was:
* Make changes in the submodule repository (rticonnextdds-connector)
* In the binding repository (rticonnextdds-connector-js) `cd` into the submodule, checkout the change and commit that
* This meant that there was a clear (and stable) relationship between any branch in this repository, and the code that would end up getting used within the submodule.

2023-12-19 11:59 UTC, samuelraeburn commented on package.json
> +    "eslint": "^7.29.0",
We don't want to include this. See CON-290. We removed these because they aren't really used, and it makes dependabot report a lot more vulnerabilities.

2023-12-19 11:59 UTC, samuelraeburn commented on package.json
> +    "eslint": "^7.29.0",
See https://github.com/rticommunity/rticonnextdds-connector-js/pull/155

2023-12-19 12:16 UTC, Alxe commented on .gitattributes
> +package-lock.json	binary
While `package-lock.json` is a text file, it's contents are managed by tools like `npm` as a "snapshot" of the packages used during last `npm install` or similar.  This makes changes to the file potentially noisy and human unreadable, as well as may confuse tools that think that the text changes should make sense (e.g. not moving around a lot of lines).

Specifying this file as a binary file will help tools that rely on verbs like `git diff` to ignore the contents of the file itself. You can still use `git diff --text` to force a text representation.

If you think this is not good, I can revert this change.

2023-12-19 12:21 UTC, Alxe commented on .gitmodules
> +	branch = develop
This change only affects `git submodule update` when using the `--remote` , and is useful if we want to checkout the latest commit in the specified branch, instead of from the latest branch that we checked out.

Git will still track the specified commit that has been checked out in `rticonnextdds-connector`, so the process does not change. Given that this might be confusing but not too useful, I'll revert the change.

2023-12-20 09:34 UTC, samuelraeburn approved these changes

2023-12-20 10:03 UTC, merged