CON-298 -- Change mention of version string in doc/
rticommunity/rticonnextdds-connector-js pull request #167
Opened 2023-12-22 01:18 UTC by alvinkrebs

Update the doc/conf.py and doc/release_notes.rst to show new version 1.3.0.

2023-12-28 16:42 UTC, rkorte commented on docs/release_notes.rst
> +
@Alxe, do you want to go ahead and add a statement here like we did for Version 1.2.2?

*RTI Connector* 1.3.0 is built on `RTI Connext 7.3.0 <https://community.rti.com/documentation/rti-connext-730>`__.

Or we could wait until we make the other doc updates (but might as well do it now? I get nervous about blank sections in the documentation that we might forget to update ...)

2023-12-28 16:51 UTC, Alxe commented on docs/release_notes.rst
> +
Let's do this, we can continue filling the blanks later on.

@alvinkrebs Can you add @rkorte's suggestion to the "Version 1.3.0" section? Namely:
```
Version 1.3.0
-----------------

*RTI Connector* 1.3.0 is built on 
`RTI Connext DDS 7.3.0 <https://community.rti.com/documentation/rti-connext-dds-730>`__.
```

2023-12-28 16:52 UTC, Alxe requested changes
While everything looks good, let's add @rkorte's suggestion.

2023-12-28 19:35 UTC, alvinkrebs commented on docs/release_notes.rst
> +
Ok, I've added that comment

2023-12-29 06:40 UTC, rkorte commented
How do I see the built docs via GitHub? (I thought Sam showed me once, but I forget.)

2023-12-29 11:03 UTC, Alxe approved these changes

2023-12-29 16:38 UTC, merged

2023-12-29 20:04 UTC, alvinkrebs commented
> @alvinkrebs or @Alxe, how do I see the built docs via GitHub? (I thought Sam showed me once, but I forget.)

You can always pop over to https://github.com/rticommunity/rticonnextdds-connector-js/tree/develop/docs and look at any file. But make sure you've chosen the branch you'd like to see.