COMMUNITY-80 | Add a new stage in the build_and_test script to publish connector into our internal npm server when a new tag is pushed
rticommunity/rticonnextdds-connector-js pull request #190
Opened 2024-02-19 17:27 UTC by ManuelJNunez

In this PR I added a new stage to publish connector into our internal server when a new tag with format `v\d+\.\d+\.\d+` is pushed. That new stage will call a bash script that I implemented for that purpose.

2024-02-19 17:30 UTC, ManuelJNunez commented
[ ] Pending on https://github.com/rticommunity/rticonnextdds-connector/pull/95

2024-02-21 08:21 UTC, Alxe requested changes

2024-02-21 08:21 UTC, Alxe commented on resources/scripts/publish.sh
> +version_to_publish=$package_version-$modified_build_id
We need to make sure that this script fits both internal and external uploads. For external uploads, we don't want to modify the version of the package.

2024-02-21 08:21 UTC, Alxe commented on ci_config.yaml
> +publish_version: "lts"
```suggestion
publish_version: "20"
```

While we're most likely going to use the LTS for publication, I think it's best we make that choice explicitly.

2024-02-21 08:21 UTC, Alxe commented on resources/jenkins/build_and_test.groovy
> +                    dir("${env.WORKSPACE}/${CI_CONFIG['publish_version']}") {
Is `CI_CONFIG` valid in this scenario? Based on previous code, this is only true when the node version is not predefined in the job name.

2024-02-21 11:10 UTC, Alxe approved these changes

2024-02-21 11:16 UTC, merged