Update docs for CON-209
rticommunity/rticonnextdds-connector-js pull request #20
Opened 2020-08-25 17:47 UTC by alexcamposruiz

2020-08-26 08:34 UTC, samuelraeburn commented on rticonnextdds-connector.js
> +   *   `URL Groups <https://community.rti.com/static/documentation/connext-dds/current/doc/manuals/connext_dds_professional/users_manual/index.htm#users_manual/URL_Groups.htm>`__
https://community.rti.com/static/documentation/connext-dds/current/doc/manuals/connext_dds_professional/users_manual/index.htm#users_manual/URL_Groups.htm is broken

2020-08-26 08:35 UTC, samuelraeburn requested changes

2020-08-26 08:35 UTC, samuelraeburn commented on rticonnextdds-connector.js
> +   *   `URL Groups <https://community.rti.com/static/documentation/connext-dds/current/doc/manuals/connext_dds_professional/users_manual/index.htm#users_manual/URL_Groups.htm>`__
That link doesn't work (I guess it used to... Maybe this is related to CON-211?

2020-08-27 15:25 UTC, alexcamposruiz commented on rticonnextdds-connector.js
> +   *   `URL Groups <https://community.rti.com/static/documentation/connext-dds/current/doc/manuals/connext_dds_professional/users_manual/index.htm#users_manual/URL_Groups.htm>`__
It's the future dir structure in Hercules.

2020-08-27 15:27 UTC, samuelraeburn approved these changes

2020-08-27 15:31 UTC, merged