IRONSIDE-1156 -- merge release/connector/1.3.0 to develop
rticommunity/rticonnextdds-connector-js pull request #202
Opened 2024-04-15 17:34 UTC by alvinkrebs

Per the 7.3.0 release requirements, merge the 1.3.0 release to develop.
After this is approved merge develop to master.

There was a ci_config.yaml conflict.
The rticonnextdds-connector submodule pointer has changed to the release/connector/1.3.0 branch.

2024-04-19 07:03 UTC, Alxe requested changes
The [`rticonnextdds-connector/config.yaml`](https://github.com/rticommunity/rticonnextdds-connector/compare/6886e8aef0a458e6a6c6ff76bf07d378ceb57b0c...4f9e76dcd870d56ec0f31c1b60ad22cda1a0a235#diff-d8d0422389f03d783e32e627250fe29834bd09c6361640d1ff00661dd6820034) file needs update as well, version should stay as `latest`.

2024-04-19 15:31 UTC, Alxe requested changes

2024-04-19 15:31 UTC, Alxe commented on rticonnextdds-connector
`config.yaml` needs to have `latest` as version.

2024-06-11 15:54 UTC, rkorte commented on docs/release_notes.rst
> +^^^^^^^^^^^^^^^^^^^^^
I think the heading is correct, but the text underneath it is weird: "1.0.0 is the first official release of RTI Connector for JavaScript ..." 

@Alxe, do we need to create a new section at the very bottom of this file called Version 1.0.0, with this introductory text?

2024-06-11 16:34 UTC, Alxe approved these changes

2024-06-12 03:24 UTC, rkorte approved these changes

2024-06-12 17:27 UTC, rkorte requested changes

2024-06-12 17:27 UTC, rkorte commented on docs/release_notes.rst
>  Version 1.0.0
This still isn't in the right place. See the output: https://jenkins-community.rti.com/job/ci/job/connector-js/job/rticonnextdds-connector-js-doc/view/change-requests/job/PR-202/Connector_20Documentation/

It should be section 8.3.6.

2024-06-12 17:58 UTC, rkorte approved these changes

2024-06-12 19:41 UTC, merged