IRONSIDE-1166 -- final merge of latest release, release/connector/1.3.0 to master.
rticommunity/rticonnextdds-connector-js pull request #205
Opened 2024-07-05 19:48 UTC by alvinkrebs

**Merge release 1.3.0 to master.**

1. Several modifications to the rticonnextdds-connector. The largest being we no longer commit libraries. So, you'll see the lib/ directory disappear.
2. Supporting this change are various configuration changes and new scripts. README and LICENSE were also adjusted.

2024-07-05 20:14 UTC, elainerti approved these changes

2024-07-05 20:17 UTC, elainerti reviewed
Validation seems to fail. @ManuelJNunez  any idea how to address this?

2024-07-05 20:17 UTC, ManuelJNunez approved these changes

2024-07-05 20:19 UTC, ManuelJNunez commented
> Validation seems to fail. @ManuelJNunez  any idea how to address this?

This is because of a backport on Node that caused problems with one of our Third-Party dependencies. This was already addressed on develop.

2024-07-05 20:20 UTC, ManuelJNunez commented
> Validation seems to fail. @ManuelJNunez  any idea how to address this?

One option is to modify the ci_config.yaml to use the version that worked correctly before the last Node update.

2024-07-05 20:29 UTC, ManuelJNunez requested changes

2024-07-05 20:29 UTC, ManuelJNunez commented on ci_config.yaml
> +  - "18"
18.19 should work

2024-07-05 20:29 UTC, ManuelJNunez commented on ci_config.yaml
> +  - "20"
20.11 should work

2024-07-05 23:01 UTC, alvinkrebs commented on ci_config.yaml
> +  - "20"
I don't see these values in develop or release/connector/1.3.0.

2024-07-06 07:57 UTC, ManuelJNunez commented on ci_config.yaml
> +  - "20"
Yes, but I think that it is better to change it than seeing master (a branch that should be stable and the first that you see when you open the repository) with a failing CI

2024-07-08 14:39 UTC, Alxe commented on ci_config.yaml
> +  - "20"
For reference, `release/connector/1.3.0` doesn't have #203 (CON-304) applied, thus CI will fail as @ManuelJNunez said.

I agree we should narrow our Node versions used in CI to the ones that we know will work. We can continue the discussion offline on whether `master` makes sense or not.

@alvinkrebs Based on #198, we should have these versions be:
```
node_versions:
  - "18.19"
  - "19"
  - "20.11"
```

19 is not a LTS release, so the change shouldn't have been backported but I've not confirmed this.

2024-07-08 19:55 UTC, closed without merging

2024-07-08 19:56 UTC, alvinkrebs commented
Since we are changing source, we need a feature branch.