CON-304 documentation changes (1.3.0)
rticommunity/rticonnextdds-connector-js pull request #210
Opened 2024-07-19 09:18 UTC by Alxe

Also, make minor fixes to Release Notes.

2024-07-19 15:52 UTC, elainerti requested changes

2024-07-19 15:52 UTC, elainerti commented on docs/release_notes.rst
> -*RTI Connector* 1.0.0 is built on `RTI Connext DDS 6.0.1 <https://community.rti.com/documentation/rti-connext-dds-601>`__.
I think we should at least keep the line that talk about connector 1.0.0 is built on connext 6.0.1

2024-07-19 15:53 UTC, elainerti commented on docs/release_notes.rst
>  Version 1.3.0
I think the version 1.3.0 section should be moved to the previous releases section??

2024-07-19 17:44 UTC, rkorte commented on docs/release_notes.rst
>  Version 1.3.0
Per Elaine, I will redo this PR against the release branch, release/connector/1.3.1.

2024-07-19 23:14 UTC, rkorte submitted a review, later dismissed
Per Elaine, we need to recreate this change against release/connector/1.3.1. I will do that, and then we can decline this one.

2024-07-19 23:22 UTC, rkorte commented on docs/release_notes.rst
>  Version 1.3.0
I change my mind, I will ask Lissa and Adelle to work on this.

2024-07-22 09:26 UTC, Alxe reviewed
I updated the PR with the applied feedback and a few other fixes.

2024-07-22 09:26 UTC, Alxe commented on docs/release_notes.rst
> -*RTI Connector* 1.0.0 is built on `RTI Connext DDS 6.0.1 <https://community.rti.com/documentation/rti-connext-dds-601>`__.
This has been moved to the bottom of the document. It was placed in an incorrect place as part of [this PR](https://github.com/rticommunity/rticonnextdds-connector-js/pull/200/files#diff-d778557532960c8ff205506cdecb469236ec50ca060b2da4c0b9843533a43f1aL239).

See the generated output outline.

![image](https://github.com/user-attachments/assets/5a54f602-35a2-43ad-b137-915dbde061cf)

2024-07-23 18:31 UTC, lloadholt commented on docs/release_notes.rst
> +*RTI Connector* 1.3.1 is built on *RTI Connext DDS* 7.3.0.2.
```suggestion
*RTI Connector* 1.3.1 is built on *RTI Connext* 7.3.0.2.
```

2024-07-23 20:28 UTC, elainerti approved these changes

2024-07-24 13:43 UTC, lloadholt approved these changes

2024-07-24 13:44 UTC, merged