COMMUNITY-95 | Update connector libs download
rticommunity/rticonnextdds-connector-js pull request #218
Opened 2024-08-29 17:28 UTC by ManuelJNunez

2024-08-30 10:28 UTC, ManuelJNunez commented on resources/jenkins/build_and_test.groovy
> +@Library("rticommunity-jenkins-pipelines@feature/COMMUNITY-95") _
- [ ] Remove this before merging

2024-09-02 09:51 UTC, lulivi approved these changes

2024-09-02 11:31 UTC, Alxe requested changes

2024-09-02 11:31 UTC, Alxe commented on resources/scripts/publish.sh
> +jq ". += {\"rti.build-id\": \"${build_id}\"}" package.json > package.json.tmp
I've verified that `rti.build-id` is a new attribute in the manifest.

2024-09-02 11:31 UTC, Alxe commented on rticonnextdds-connector
If you're removing the scripts from the subrepo, move `VERSION` to the local repository.
We can informally deprecate and later on remove the submodule to ease maintenance.

2024-09-05 08:22 UTC, Alxe approved these changes

2024-09-05 09:52 UTC, lulivi approved these changes

2024-09-05 09:52 UTC, merged