DOC-532: Update Connector copyrights
rticommunity/rticonnextdds-connector-js pull request #222
Opened 2024-09-10 17:58 UTC by lloadholt

Updated copyright year in conf.py
Updated copyright year and text in copyright_license.rst

2024-09-12 00:29 UTC, rkorte commented on docs/copyright_license.rst
>  OpenSSL Project for use in the OpenSSL Toolkit (http://www.openssl.org/).
Remove the line that has "© 2022 RTI" on it.

2024-09-12 00:33 UTC, rkorte commented on docs/copyright_license.rst
>  © 2024 Real-Time Innovations, Inc. |br|
Here is the output associated with this PR, following the instructions [here](https://docs.google.com/document/d/1xxk0CwrAliVZsqHXORZfDtTH3o8voA0ZTikXBldmYDA/edit#heading=h.e8wjzzaup9cn): https://jenkins-community.rti.com/job/ci/job/connector-js/job/rticonnextdds-connector-js-doc/view/change-requests/job/PR-222/Connector_20Documentation/copyright_license.html#

2024-09-12 00:34 UTC, rkorte commented on docs/copyright_license.rst
> -
I'm not sure we should delete this for Connector ... it seems specific to Connector.

I suggest keeping it for now and getting Legal's approval separately.

2024-09-12 00:34 UTC, rkorte requested changes
see other comments I left

2024-09-17 04:08 UTC, rkorte requested changes
I'm not sure you should delete the lines "RTI Connector for JavaScript is part of the ..." (starting on line 16)?

2024-09-24 01:37 UTC, rkorte commented
> @lloadholt Can you riview and apply @rkorte's comments?

Lissa is out on vacation, so I made the updates.

2024-09-24 01:44 UTC, rkorte commented
How can I reply to a comment so that my reply appears directly below the comment? This is the only option Github gives me, and then it puts the quote reply at the bottom of the Conversation.
![github_reply_comment](https://github.com/user-attachments/assets/e50c3f1c-3333-4f8d-8ec7-8e7f85b47e29)

2024-09-24 15:18 UTC, Alxe commented
> @Alxe, how can I reply to a comment so that my reply appears nested directly below the comment? This is the only option Github gives me, and then it puts the quote reply at the bottom of the Conversation: ![github_reply_comment](https://private-user-images.githubusercontent.com/36715349/370098449-e50c3f1c-3333-4f8d-8ec7-8e7f85b47e29.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxOTEzODQsIm5iZiI6MTcyNzE5MTA4NCwicGF0aCI6Ii8zNjcxNTM0OS8zNzAwOTg0NDktZTUwYzNmMWMtMzMzMy00ZjhkLThlYzctOGU3Zjg1YjQ3ZTI5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDE1MTgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiYmU2NWNmZDhjYmEwYTM1OWE2MTc4ZGI4Y2FjYjUwZjFiMDExMjZlYTg2Y2EzMmQ3MTM0ZTFkOWIwNTAwMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bbc31Pn9r-xOxmCK80nk-fWYA-KKnWL78iTgZ3H-fp4)

The best you can do is "quote reply". Only comments done in the file overview can be nested, unlike in Bitbucket.

2024-09-24 15:19 UTC, Alxe approved these changes

2024-09-24 15:44 UTC, merged