CON-325: Update copyright page, index, and conf.py
rticommunity/rticonnextdds-connector-js pull request #228
Opened 2024-10-23 17:01 UTC by lloadholt

- Update year and make corrections in copyright
- Add 'Contents' heading in index
- Update referenced css file in conf

2024-10-25 06:05 UTC, rkorte commented on docs/conf.py
> +        '2025, Real-Time Innovations, Inc.',
2020-2025
The footer copyright year uses the first_year-second_year format, too. See other Sphinx docs such as https://community.rti.com/static/documentation/connext-dds/7.4.0/doc/manuals/connext_dds_professional/getting_started_guide/index.html.

2024-10-25 06:07 UTC, rkorte commented on docs/conf.py
> +        '2025, Real-Time Innovations, Inc.',
(at least, all other Sphinx docs should; I noticed at least one that forgot to)

2024-10-25 06:11 UTC, rkorte commented on docs/index.rst
> +:contents:`Contents`
Can you just use Contents with a single underline to make it a normal heading? Then you don't need the new lines above. The font looks a little off. I think just make it a normal heading.

2024-10-25 06:12 UTC, rkorte requested changes
see comments

2024-10-28 13:24 UTC, Alxe commented on docs/conf.py
> +    app.add_css_file('theme_overrides.css')
Is there any reasoning as for why you've made this change?
I do approve of the change, as [`add_stylesheet` is a legacy alias}(https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.add_css_file), but I'm curious if you found this to be a problem due to a Sphinx upgrade or something.

2024-10-28 13:24 UTC, Alxe requested changes

2024-10-28 13:24 UTC, Alxe commented on docs/conf.py
> +html_logo = "static/rti-logo-FINALv2-White-OrangeDot.png"
Leave an trailing, empty line before the end of the file.

2024-10-28 16:47 UTC, lloadholt commented on docs/conf.py
> +    app.add_css_file('theme_overrides.css')
I got an error msg advising to make this change when building the docs locally.

2024-10-29 04:01 UTC, rkorte approved these changes
looks good

2024-10-29 12:53 UTC, Alxe approved these changes

2024-10-29 12:53 UTC, Alxe commented on docs/conf.py
> +    app.add_css_file('theme_overrides.css')
That error message must've been related to using a version of Sphinx which removed `add_stylesheet`.

I think the change is okay but, going forwards, you should attempt to use the [`requirements.txt` file in the `docs/`folder](https://github.com/rticommunity/rticonnextdds-connector-js/blob/master/docs/requirements.txt) whenever you're installing Sphinx.
This would avoid such problems.

2024-10-29 19:48 UTC, merged