CON-215: Added release notes
rticommunity/rticonnextdds-connector-js pull request #25
Opened 2020-09-10 13:15 UTC by samuelraeburn

2020-09-10 13:43 UTC, samuelraeburn commented
https://jira.rti.com/issues/?jql=project%20%3D%20CON%20AND%20fixVersion%20%3D%20Hercules%20AND%20%22Resolved%20Versions%22%20is%20EMPTY

2020-09-10 16:15 UTC, samuelraeburn commented on docs/release_notes.rst
> +Version 2.0.0 (TODO Numebring)
```suggestion
Version 1.1.0
```

2020-09-10 16:15 UTC, samuelraeburn commented on docs/release_notes.rst
> +~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```suggestion
~~~~~~~~~~~~~
```

2020-09-10 16:16 UTC, samuelraeburn commented on docs/release_notes.rst
> +What's New in 2.0.0
```suggestion
What's New in 1.10
```

2020-09-10 16:16 UTC, samuelraeburn commented on docs/release_notes.rst
> +What's Fixed in 2.0.0
```suggestion
What's Fixed in 1.10
```

2020-09-10 16:16 UTC, samuelraeburn commented on docs/release_notes.rst
> +What's Fixed in 1.10
```suggestion
What's Fixed in 1.1.0
```

2020-09-10 16:17 UTC, samuelraeburn commented on docs/release_notes.rst
> +What's New in 1.10
```suggestion
What's New in 1.1.0
```

2020-11-12 16:26 UTC, alexcamposruiz requested changes

2020-11-12 16:26 UTC, alexcamposruiz commented on docs/release_notes.rst
> +Support added for Node.js version 12
We also support Node 13. Also, we should mention that 12.19 is not supported due to a bug in Node 12.19. (See new footnote in getting started)

2020-11-12 16:26 UTC, alexcamposruiz commented on docs/release_notes.rst
> +The SampleInfo class in *Connector* has been extended to provide access to the
link to SampleInfo class

2020-11-12 16:26 UTC, alexcamposruiz commented on docs/release_notes.rst
> +JSON Object).
@samuelraeburn can you link to wherever we have an example of this?

2020-11-12 16:26 UTC, alexcamposruiz commented on docs/release_notes.rst
> +key values in the sample should be accessed.
Add link to new functionality/examples

2020-11-12 16:26 UTC, alexcamposruiz commented on docs/release_notes.rst
> +[RTI Issue ID CON-209]
Why do we use different formatting for bugs than for new features (`.. CON-188`)

2020-11-12 16:26 UTC, alexcamposruiz commented on docs/advanced.rst
> +Advanced Topics
These changes may be breaking links such as `ref:Advanced topics`

2020-11-12 16:26 UTC, alexcamposruiz commented on docs/output.rst
> +Writing Data (Output)
These changes are likely breaking links in multiple places

2020-11-12 16:30 UTC, alexcamposruiz requested changes

2020-11-12 16:30 UTC, alexcamposruiz commented on docs/release_notes.rst
> +Version 1.1.0
We should add a note similar to this one:

```
*RTI Connector* 1.0.0 is built on `RTI Connext DDS 6.0.1 <https://community.rti.com/documentation/rti-connext-dds-601>`__.
```

2020-11-13 07:54 UTC, samuelraeburn commented on docs/release_notes.rst
> +Support added for Node.js version 12
Ok added that info here about 12.19 and node 13.
Note that Node.js v13 is actually unsupported by Node.Js. Not sure  if we want to document it here (since I doubt anybody will use it). From https://nodejs.org/en/about/releases/:
`After six months, odd-numbered releases (9, 11, etc.) become unsupported`

Let me know.

2020-11-13 08:06 UTC, samuelraeburn commented on docs/release_notes.rst
> +Version 1.1.0
Added a sentence and guessed the link to community docs for 6.1.0 as https://community.rti.com/documentation/rti-connext-dds-610

@rkorte Do you know if that link will be correct?

2020-11-13 08:08 UTC, samuelraeburn commented
In future I think we need a better way of updating Connector documentation. Around 99% of features added to Connector are added to both Python and JavaScript Connector, meaning the doc reviews are awful to do (since you end up doing everything twice).

Short term, I think the best solution is to do the reviews in series instead of parallel (i.e., pick either JavaScript or Python Connector, complete the entire doc review, then do the same changes in the other product).

What do you guys think? @alexcamposruiz @rkorte

2020-11-13 18:20 UTC, rkorte commented
> In future I think we need a better way of updating Connector documentation. Around 99% of features added to Connector are added to both Python and JavaScript Connector, meaning the doc reviews are awful to do (since you end up doing everything twice).
> 
> Short term, I think the best solution is to do the reviews in series instead of parallel (i.e., pick either JavaScript or Python Connector, complete the entire doc review, then do the same changes in the other product).
> 
> What do you guys think? @alexcamposruiz @rkorte

I think that's the best we can do as long as connector-js and connector-py docs are in different directories. Why can't we create one manual with Javascript and Python chapters? Then we could share content.

2020-11-16 09:43 UTC, samuelraeburn commented
That makes a lot of sense, alternatively we could use the common `connextdds-connector` repository to store the docs. Though we want to avoid a situation like the connextdds repository, where we have one set of doc files for 5 different language bindings, since it gets pretty confusing with all of the `\if_C` `\ifnot_JAVA`.

2021-01-07 22:51 UTC, alexcamposruiz requested changes

2021-01-07 22:51 UTC, alexcamposruiz commented on docs/release_notes.rst
> +version 12.19.0 is incompatible with Connecot for JavaScript due to a regression
``
```suggestion
version 12.19.0 is incompatible with Connector for JavaScript due to a regression
```

2021-01-11 09:02 UTC, samuelraeburn commented on docs/release_notes.rst
> +[RTI Issue ID CON-209]
See https://github.com/rticommunity/rticonnextdds-connector-py/pull/55#discussion_r547028190

2021-01-11 18:14 UTC, rkorte commented on docs/release_notes.rst
> +Version 1.1.0
Yes, it should be.

2021-01-20 19:45 UTC, alexcamposruiz approved these changes

2021-01-25 18:44 UTC, rkorte commented on docs/release_notes.rst
> +Support added for Node.js version 12
Sam, I don't see what you added about 12.19 so that I can review it.

2021-01-25 18:48 UTC, rkorte approved these changes

2021-01-25 19:19 UTC, merged