Con 211 js
rticommunity/rticonnextdds-connector-js pull request #28
Opened 2020-10-08 20:49 UTC by rkorte

Here are the same fixes to connector-js as made to connector-py to update links to other manuals, according to the new doc tree in Hercules (and community)

2020-10-09 06:49 UTC, samuelraeburn commented
@rkorte I confirmed that the issue with the LICENSE.pdf file always showing as modified is due to differences in how the file is stored on Windows and on Linux. We should make some changes to your git settings to avoid this, but for now if you commit the LICENSE.pdf I will revert it before we create a release branch.
@alexcamposruiz Sound ok?

2020-10-09 06:49 UTC, samuelraeburn approved these changes

2020-10-09 17:16 UTC, alexcamposruiz requested changes
The new links don't work. I understand we expect to update the community later on, but it looks quite risky to start adding links everywhere and not being able to check they work. Should we upload the new directory structure already?

2021-01-20 19:46 UTC, alexcamposruiz approved these changes

2021-01-22 17:54 UTC, alexcamposruiz requested changes

2021-01-22 17:54 UTC, alexcamposruiz commented on docs/features.rst
> +     - On an ``Output``, it is possible to dispose or unregister an instance (see :meth:`Output.write`). Instances are automatically registered when first written. On an ``Input`` the instance state
I would delete "Instance handles are not exposed."

2021-01-22 18:01 UTC, alexcamposruiz approved these changes

2021-01-22 18:03 UTC, merged