Added Ubuntu 16.04 to release notes (x64, Armv8)
rticommunity/rticonnextdds-connector-js pull request #47
Opened 2021-03-12 08:24 UTC by samuelraeburn

2021-03-12 15:51 UTC, alexcamposruiz approved these changes

2021-03-12 15:52 UTC, alexcamposruiz requested changes

2021-03-12 15:52 UTC, alexcamposruiz commented on docs/release_notes.rst
> +  * Ubuntu® 14.04, 16.04, 18.04, 20.04 LTS (x64)
Add Arm v8 to What's new

2021-03-12 18:07 UTC, adelleolson approved these changes

2021-03-15 09:00 UTC, samuelraeburn commented
![Screenshot from 2021-03-15 09-58-35](https://user-images.githubusercontent.com/24991686/111128458-34e4a680-8575-11eb-94d9-c0b53519c2e0.png)

2021-03-15 16:24 UTC, alexcamposruiz approved these changes

2021-03-16 10:00 UTC, merged