Feature/con 194 js - copyright updates and add logging section
rticommunity/rticonnextdds-connector-js pull request #53
Opened 2021-04-02 18:53 UTC by rkorte

2021-04-02 19:00 UTC, rkorte commented
Do any of these issues need to be fixed

- Some modules are not getting built (see [here](https://docs.google.com/document/d/1ZiaC5sZT3VuUps9IVHICb-6IhJdJPwqDO2P1ibq43AQ/edit?disco=AAAAIJ_HALU))
- Does <participant_qos> tag update to domain_participant_qos (see [CORE-11069](https://jira.rti.com/browse/CORE-11069)) affect Connector?
- The new feature about disposed instances says "Instance handles are not exposed" in python version, but not js version. Should they be the same?

2021-04-02 23:45 UTC, alexcamposruiz requested changes

2021-04-02 23:45 UTC, alexcamposruiz commented on docs/copyright_license.rst
> +April 2021. |br|
I thought we only updated the (c) year when the product changed in a major fashion, but not for normal releases.

2021-04-02 23:45 UTC, alexcamposruiz commented on docs/copyright_license.rst
> +his product includes cryptographic software written by Eric Young
```suggestion
This product includes cryptographic software written by Eric Young 
```

However, Connector doesn't include any security features, Connext Pro does.

2021-04-05 12:52 UTC, samuelraeburn approved these changes

2021-04-05 22:55 UTC, rkorte commented on docs/copyright_license.rst
> +his product includes cryptographic software written by Eric Young
@alexcamposruiz, what do you recommend here? Should I delete the whole "The security features of this product ..." paragraph (keep in mind it was there even in 1.0.0, although without my additions here)? 

According to Legal, the sentences I added have to accompany that first sentence from now on, and I have made that change in all products. Per Legal, it's OK if the product doesn't even use security features, having it there "just in case" or even when not needed is OK, in order to product just one copyright statement that works for all books.

Given that, we could, for Connector:
- delete the whole paragraph since Connector doesn't have security features
- keep it since it interoperates with Pro, which can use security features
- rewrite it to say something like, "The security features of RTI Connext include ..." if it just feels too strange to include this statement for Connector (I would want to run that by Legal, though)
-

2021-04-05 23:56 UTC, alexcamposruiz commented on docs/copyright_license.rst
> +his product includes cryptographic software written by Eric Young
It makes sense to keep it so we have a single copyright statement.

2021-04-05 23:59 UTC, alexcamposruiz commented
> Do any of these issues need to be fixed
> 
> * Some modules are not getting built (see [here](https://docs.google.com/document/d/1ZiaC5sZT3VuUps9IVHICb-6IhJdJPwqDO2P1ibq43AQ/edit?disco=AAAAIJ_HALU))
> * Does <participant_qos> tag update to domain_participant_qos (see [CORE-11069](https://jira.rti.com/browse/CORE-11069)) affect Connector?
> * The new feature about disposed instances says "Instance handles are not exposed" in python version, but not js version. Should they be the same?

@samuelraeburn can you look into these issues?

2021-04-06 06:41 UTC, samuelraeburn commented
(Responses inline)

> Do any of these issues need to be fixed
> 
> * Some modules are not getting built (see [here](https://docs.google.com/document/d/1ZiaC5sZT3VuUps9IVHICb-6IhJdJPwqDO2P1ibq43AQ/edit?disco=AAAAIJ_HALU))

**See attached screenshot, the links in that google doc are dead now, but for me locally all classes are built for both APIs. Can you check if it is still an issue with the latest doc builds?**
![Screenshot from 2021-04-06 08-40-54](https://user-images.githubusercontent.com/24991686/113669313-dd3ce500-96b3-11eb-8035-e70f7c4379fc.png)


> * Does <participant_qos> tag update to domain_participant_qos (see [CORE-11069](https://jira.rti.com/browse/CORE-11069)) affect Connector?

**It does affect Connector, but I think I already fixed it. Have you found some instances of participant_qos that I have missed?**

> * The new feature about disposed instances says "Instance handles are not exposed" in python version, but not js version. Should they be the same?

**I have committed this change to this branch**

2021-04-06 18:34 UTC, alexcamposruiz approved these changes

2021-04-07 20:09 UTC, merged