HERCULES-186: updates to licenses doc for javascript
rticommunity/rticonnextdds-connector-js pull request #55
Opened 2021-04-14 17:35 UTC by rkorte

required by Legal (they don't care where we put it as long as it's in there)

2021-04-14 17:49 UTC, alexcamposruiz requested changes

2021-04-14 17:49 UTC, alexcamposruiz commented on docs/copyright_license.rst
> +    lua.1.0 module (version 5.2).
> We have the source code checked into the connextdds repository in the lua.1.0 module (version 5.2).

This sounds weirdly specific. A customer doesn't know we have a "connextdds repository", let alone a "lua.1.0 module". Should we just say "the source code is checked into our internal code repositories"

2021-04-15 23:47 UTC, rkorte commented on docs/copyright_license.rst
> +    lua.1.0 module (version 5.2).
I modified it, with Ching's and Elaine's approval

2021-05-03 15:28 UTC, alexcamposruiz approved these changes

2021-05-03 16:18 UTC, merged