CON-223: Removed max_objects_per_thread API
rticommunity/rticonnextdds-connector-js pull request #60
Opened 2021-05-25 12:47 UTC by samuelraeburn

The behaviour of max_objects_per_thread has changed in the core, and it now
grows dynamically, meaning we no longer need to provide a way of setting it.

2021-05-25 14:21 UTC, samuelraeburn commented
- [ ] wait for Ironside release. Until then we do not have the required changes in CORE.

2021-06-02 18:50 UTC, alexcamposruiz requested changes

2021-06-02 18:50 UTC, alexcamposruiz commented on rticonnextdds-connector.js
> -  static setMaxObjectsPerThread (value) {
Instead of deleting the function and potentially breaking user applications, is there a way to mark it as deprecated and leave an empty implementation?

2021-06-02 18:50 UTC, alexcamposruiz commented on test/nodejs/test_rticonnextdds_connector.js
> +  it('Connector should not segfault if deleted twice', async function () {
Does this unit test require a fix for CON-200 first?

2021-06-08 06:32 UTC, samuelraeburn commented on test/nodejs/test_rticonnextdds_connector.js
> +  it('Connector should not segfault if deleted twice', async function () {
It does not fail in JS, I don't think any fix is required.

2021-06-18 23:50 UTC, alexcamposruiz approved these changes

2021-06-24 12:58 UTC, merged