:Feature/64 bit support
rticommunity/rticonnextdds-connector-js pull request #64
Opened 2021-07-02 09:54 UTC by samuelraeburn

Docs

2021-07-02 18:39 UTC, rkorte commented
I have completely forgotten how to enter a comment on a specific line in a changed file. 

Anyway, I decided to make my edits in your branch and have you review them, if that's OK. A couple notes on my edits:

- I changed "that" to "which," which I _think_ is correct. I believe you mean that "Connector relies on a framework that only contains a single number type" (and, crucially, that number type is an IEEE-754 floating-point number). You do _not_ mean (I think) that Connector relies on a framework that contains numerous number types, and only one of them is an IEEE-754 floating-point number (which is the meaning if you use "that").
- I changed "we" to "Connector" to be more formal and specific; however, if the subject of that sentence isn't "Connector" but something else and you don't want to get into all that, you can change it back to "we." But if the subject is, say, "RTI Connext DDS," then you should say so (i.e., say who/what does "not use JavaScript's BigInt representation").

2021-07-02 18:41 UTC, rkorte requested changes
I added a commit with my suggested changes.

2021-07-02 18:43 UTC, rkorte commented
UPDATE: I figured out how to enter comments. I had to click Add Review first.

2021-09-15 17:55 UTC, rkorte approved these changes

2021-09-29 14:28 UTC, alexcamposruiz approved these changes

2021-09-29 14:28 UTC, alexcamposruiz commented on docs/data.rst
> +64-bit values with an absolute value greater than 2^53 can be retrieved via:
"greater" or "greater or equal"?

2021-09-29 14:28 UTC, alexcamposruiz commented on docs/data.rst
> +If your type contains uint64 or int64 members, and you expect them to be larger
stylize int64 and uint64 (``)

2021-09-29 14:28 UTC, alexcamposruiz commented on docs/data.rst
> +64-bit values with an absolute value greater than 2^53 can be retrieved via:
I see the note below now.

2021-09-30 13:57 UTC, merged