Update package-lock.json for version 1.2.0-rc2
rticommunity/rticonnextdds-connector-js pull request #89
Opened 2021-11-19 19:21 UTC by alvinkrebs

Last step before test availability.

2021-11-19 19:33 UTC, alexcamposruiz commented on package-lock.json
> +    "node_modules/@babel/code-frame": {
Why all these additions?

2021-11-19 20:50 UTC, alvinkrebs commented on package-lock.json
> +    "node_modules/@babel/code-frame": {
These are the diffs occurring after running "npm i --package-lock-only" 
This file isn't published though, so, not sure why it has to be updated.

2021-11-20 00:56 UTC, alexcamposruiz commented on package-lock.json
> +    "node_modules/@babel/code-frame": {
@samuelraeburn can you review this?

2021-11-22 10:21 UTC, samuelraeburn commented on package-lock.json
> +    "node_modules/@babel/code-frame": {
When I run npm install my package-lock.json file comes back as modified when using this branch.

Also, you must have Node.JS v15 or higher installed since the lockfileVersion was updated to 2 (npm v7 uses lockfileVersion 2) -- I wouldn't recommend doing any Connector npm operations with anything other than npm v6 until we support higher versions. @alexcamposruiz That is the reason there are so many modifications, it uses a different format for the file in npm >= v7.

If you install npm v6, and run in the github repository `npm install` (or you can do `--package-lock-only`) it should have a much smaller diff.

In general for this PR it doesn't need to be done for every iteration of install testing, just do it once when we are ready to release

2021-11-22 10:21 UTC, samuelraeburn requested changes
using wrong version of npm (see larger comment in above thread)

2021-11-30 22:17 UTC, alvinkrebs commented on package-lock.json
> +    "node_modules/@babel/code-frame": {
Did the following steps, after which, there were no differences in package-lock.json from 1ae1ba7f8 (Sam's last commit to this file). Is that expected?

brew uninstall --ignore-dependencies node
brew uninstall --force node
brew update
brew install nvm

nvm ls-remote
nvm instll node     <-- this step downloads v17.2.0
npm install npm@6.13.3 -g
npm --version
-> 6.13.3

2021-12-09 16:22 UTC, closed without merging