CON-254: Document unsupport Node.JS v11
rticommunity/rticonnextdds-connector-js pull request #93
Opened 2021-11-23 17:10 UTC by samuelraeburn

2021-11-23 18:57 UTC, alexcamposruiz requested changes

2021-11-23 18:57 UTC, alexcamposruiz commented on docs/release_notes.rst
> +   Node.js prior to v10.20.x. It is also not compatible with any version of Node.js v11.
mention why it's not compatible with any v11.

2021-11-23 18:57 UTC, alexcamposruiz commented on docs/release_notes.rst
> +*RTI Connector for JavaScript* has been tested with Node.js versions 10.24.0 and 12.22.7.
Delete this paragraph. Let's just mention which versions work.

2021-11-24 08:21 UTC, samuelraeburn commented on docs/release_notes.rst
> +   Node.js prior to v10.20.x. It is also not compatible with any version of Node.js v11.
The same reason that we do not support any version older than 10.20.0, they do not have this commit: https://github.com/nodejs/node/pull/28682

2021-11-29 15:54 UTC, alexcamposruiz requested changes

2021-11-29 15:54 UTC, alexcamposruiz commented on docs/release_notes.rst
> +   these versions of Node.js do not support n-api, which is used by some of our
```suggestion
   these versions of Node.js do not support n-api, which is used by some of its
```

2021-11-29 20:43 UTC, rkorte requested changes

2021-11-29 20:43 UTC, rkorte commented on docs/release_notes.rst
> +   these versions of Node.js do not support n-api, which is used by some of its
change "its" to "their" (you're talking about these versions, plural, of Node.js that do not support n-api)

2021-11-29 20:43 UTC, rkorte commented on docs/release_notes.rst
> +
Both here and in the above footnote, Connector should be italicized

2021-11-29 20:43 UTC, rkorte commented on docs/release_notes.rst
>  What's New in 1.2.0
This was all a little hard for me to follow. Could we just say the following:

Connector works with Node.js versions 10.20 through 13.x.x, except for versions 11 and 12.19. (Versions of Node.js prior to v10.20.x and version Node.js v11 do not support n-api, which is used by some of Connector's dependencies. Node.js v12.19.0 is not compatible with Connector because of a regression introduced in that version of Node.js.)

(You can make that parenthetical a footnote, if you really want to remove it further from the reader's attention.)

(Saying that Connector works with versions 12.18.x and 12.20.x threw me, because we already say that it works with versions 10.20 through 13.x.x (except for 12.19). It makes me doubt whether 12.19 really is the only version that doesn't work.)

2021-11-29 20:43 UTC, rkorte commented on docs/release_notes.rst
> +   these versions of Node.js do not support n-api, which is used by some of its
Actually, I'm not sure ... whose dependencies are you talking about? Connector's? Maybe you mean Connector's. Anyway, it's not clear, so please specify. (But see my other comment first.)

2021-11-30 14:26 UTC, samuelraeburn commented
Screenshot of updated docs attached
![Screenshot from 2021-11-30 15-24-31](https://user-images.githubusercontent.com/24991686/144065348-c71fd292-2d4f-42f6-becd-da3090619be4.png)

2021-11-30 19:17 UTC, alexcamposruiz requested changes

2021-11-30 19:17 UTC, alexcamposruiz commented on docs/release_notes.rst
> +on x64 CPUs.
It has been validated on x64 *and* arm64 (via x64 libraries)

2021-11-30 19:17 UTC, alexcamposruiz commented on docs/release_notes.rst
> -  * CentOS™ 6.0, 6.2-6.4, 7.0 (x64)
don't remove these versions. Connector still works in all these CentOS, RedHat and Ubuntus.

2021-11-30 19:17 UTC, alexcamposruiz commented on docs/release_notes.rst
> -  * Windows 8 (x64)
Connector still works on Windows 8

2021-12-15 16:07 UTC, alexcamposruiz approved these changes

2021-12-15 17:36 UTC, rkorte approved these changes
I notice Alex says that Windows 8 is still supported, but this PR shows it as still deleted. Still, I'm approving.

2021-12-15 17:42 UTC, merged